name: Deploy via Jenkins Local Runner

on:
  push:
    branches:
      - main

jobs:
  trigger-jenkins:
    runs-on: self-hosted
    steps:
      - name: Trigger Jenkins via localhost
        run: |
          curl -X POST "http://localhost:8080/job/EstoqueToner-Pipeline/build?token=estoque_token"
