name: Deploy via Jenkins

on:
  push:
    branches:
      - main

jobs:
  Trigger-Jenkins:
    runs-on: ubuntu-latest
    env:
      JENKINS_URL: http://localhost:8080
      JENKINS_USER: geolab
      JENKINS_API_TOKEN: 11fe5a5985c7d20682413a77386e4d24f2
      JENKINS_JOB: EstoqueToner-Pipeline
      JENKINS_JOB_TOKEN: estoque_token

    steps:
      - name: Trigger Jenkins via crumb
        shell: bash
        run: |
          CRUMB=$(curl -s -u "$JENKINS_USER:$JENKINS_API_TOKEN" "$JENKINS_URL/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,\":\",//crumb)")
          echo "Crumb: $CRUMB"

          curl -X POST "$JENKINS_URL/job/$JENKINS_JOB/build?token=$JENKINS_JOB_TOKEN" \
            -u "$JENKINS_USER:$JENKINS_API_TOKEN" \
            -H "$CRUMB"
