name: Deploy via Jenkins

on:
  push:
    branches:
      - main

jobs:
  Trigger-Jenkins:
    runs-on: self-hosted  # <- usa o runner da sua rede
    steps:
      - name: Trigger Jenkins Job
        run: |
          curl -X POST "http://localhost:8080/job/EstoqueToner-Pipeline/build?token=${{ secrets.JENKINS_TOKEN }}"
